### ISSUE TITLE
Initial modal checkbox and button margin

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-viewer-app#1]
**Describe the bug**
On the initial welcome modal panel, the checkbox and the accept button are to close to margins

![Captura de pantalla 2023-07-21 083234](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/163e0a3b-beb8-4527-8c03-9c6a37003329)

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)
