### ISSUE TITLE
Button "Cambiar aplicación" and "Cambiar territorio" not working

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-viewer-app#10]
**Describe the bug**
Inside the viewer app, when the map is loaded and functional, there's a menu at the top right corner where we can change language, log out and change the application or the territory. Buttons to change the application and the territory don't seem  to be working.

**To Reproduce**
1. Open viewer app
2. Click on the top right menu button
3. Click on change application or change territory button

**Expected behavior**
A small popup showing the different applications or territories available for the user currently logged in.

**Screenshots**
![image](https://github.com/sitmun/sitmun-viewer-app/assets/45626106/01b412a4-da90-415c-a532-6bfa6095f83f)

**Comment by fjlopez** [comment]
@mvinent @silmeUsil0001 which should be the priority of this bug?

**Comment by mvinent** [comment]
I would say this is a blocker, it seems to me a basic feature in the SITMUN environment

**Comment by daniboube** [comment]
The change territory or switch app buttons only worked if there was some other option to switch to. However, if this change was not possible, the user was not informed in any way.

With this fix, buttons are hidden if this condition is met, and are only shown if there is more than one territory to switch to for an application or more than one application using that territory. For example, for application 12, both buttons are hidden, but for application 15, it is possible to switch territories.

**Comment by fjlopez** [comment]
@mvinent could you review if this issue is solved?
