### ISSUE TITLE
Layer Info panel does not scroll (review JS script for all overwritten control)

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-viewer-app#13]
**Describe the bug**
Layer Info panel does not scroll when info button is clicked on multiple layers added to the map´

**To Reproduce**
1. Open viewer
2. Add multiple layers to the map
3. On loaded layers panel, click info button for any displayed layer
4. Info layer appears inside right panel but scroll is not allowed.

**Expected behavior**
Scroll must be allowed.  If another panel is displayed (for example tree layer panel) and then loaded layers panel is shown again, then scroll bar appears

**Related issues**

- #19 

**Screenshots**

![Captura de pantalla 2023-09-04 a les 7 26 33](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/4c56ea95-ae7c-4da7-a33a-d4909f382898)

Once another panel is displayed, then scroll bar appears:
![Captura de pantalla 2023-09-04 a les 7 26 50](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/16d20959-17cc-4d4e-9b9d-1fd5e61e47f6)

**Additional context**
This occurs because some API SITNA controls has been overwritten by SILME. The original API SITNA layout has been also overwritten and some controls of the new version (3.0) may be not responding properly in SILME layout.

So, it is needed to review all control functionallity of any control in this new version with new layout.

**Comment by fjlopez** [comment]
This issues is an example of issues that #19 should address.

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)
