### ISSUE TITLE
Add file control is not set properly

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-viewer-app#16]
**Describe the bug**
Add map panel should display two controls: "Add WMS" and "add file" controls. Only "Add WMS" control is shown.

**To Reproduce**
1. Go to viewer and load application number 12
2. Click on tools panel and open "Añadir mapas"
3. Only WMS is available

**Expected behavior**
A tab panel should display two controls: WMS and file load map

**Screenshots**

Current functionallity:
![image](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/8cdf4860-12d2-4c68-89f6-2ddccf8f3bba)

Expected functionallity:
![image (1)](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/97c14c1e-8a9d-40f3-a9de-dcf1239e642e)

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)
