### ISSUE TITLE
Search input text for layer tree is not allowed

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-viewer-app#17]
**Describe the bug**
Search input text for layer tree is not allowed. Layer tree should display an input box to allow searching layers that contains some specific word in their name or description. This functionallity is properly working on API SITNA default layout.

**To Reproduce**
1. Go to Viewer and open application number 12
2. Open Layer tree panel and see that there's no input text to search on available layer

**Expected behavior**
Layer tree should display an input box to allow searching layers that contains some specific word in their name or description

**Screenshots**

This is the current functionallity:

![Captura de pantalla 2023-09-04 a les 8 56 00](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/86c918b2-0089-4dac-a4f9-00c8c5b83bd8)

This is the expected functionallity:
![Captura de pantalla 2023-09-04 a les 8 38 19](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/5a86ba7f-059c-456d-b440-d2d4620ae71b)

![Captura de pantalla 2023-09-04 a les 8 38 45](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/fe0b31c0-2331-43fa-941f-7b9eb3e8d565)

**Comment by fjlopez** [comment]
Is this a feature of SITNA or is related to the code provided by @IDEmenorca?

**Comment by mvinent** [comment]
Solved in [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/0a63e3dbb3ef919b9fdb18b7327c33dc1bdb7a2f)

**Comment by mvinent** [comment]
Solved in [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/0a63e3dbb3ef919b9fdb18b7327c33dc1bdb7a2f)
