### ISSUE TITLE
Use Service Worker to intercept all petitions and authenticate them

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-viewer-app#18]
**Expected behavior**
Implement a service worker that, when authenticated in the viewer app (meaning that we have a JWT), intercepts all HTTP petitions (or any that begin with a specified URL) and adds the JWT.

**Comment by daniboube** [comment]
As mentioned in the last project meeting (12/04), to implement this functionality we need the middleware url to be sent to us from the backend. This could come in a field within an application's configuration JSON. The name could be something like 'middleware'.

Here is an example of the expected config:
`{ application: { id: 12, title: "Visor IDE genèric", ..., middleware: "https://middleware.com" }, backgrounds: [...], groups: [...], ... }`

This example suggests that the middleware field come within the application field.
What do you think? @fjlopez

**Comment by fjlopez** [comment]
@daniboube check solution at https://github.com/sitmun/sitmun-backend-core/issues/179
