### ISSUE TITLE
Manage overriden controls and styles

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-viewer-app#19]
**Describe the issue**
In the IDEMenorca version of the api-sitna, we have some overwritten controls which are specifically styled, when we use those controls as they were originally (without being overwritten) the styles might not work fine. We should decide how to face this issue, we can use the controls strictly as they are used in the IDEMenorca version or we should adapt the style to fit the controls that we do not want to overwrite.

**Additional context**
Currently, we have the control WorkLayerManager as it is in the api-sitna while the styles are thought for the IDEMenorca version of that control (WorkLayerManagerSilme) leading to some style inconsistencies. 
e.g.: Layer Info panel does not scroll when info button is clicked on multiple layers added to the map

**Related issues**

- #13 

**Screenshots**
![image](https://github.com/sitmun/sitmun-viewer-app/assets/45626106/55edec32-0488-4749-a82f-d13c14bde361)

Once another panel is displayed, then scroll bar appears:
![image](https://github.com/sitmun/sitmun-viewer-app/assets/45626106/d682e07e-c277-4248-9e9e-c581a5ce39e8)

**Comment by fjlopez** [comment]
@silmeUsil0001 which should be the priority of this bug?

**Comment by mvinent** [comment]
Solved on previous commits
