### ISSUE TITLE
Initial extension

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-viewer-app#2]
**Describe the bug**
On public app the initial extension is not set properly

![Captura de pantalla 2023-07-21 083550](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/5d01bcaa-074c-49ec-bd58-19b87efd4fab)

**Comment by mvinent** [comment]
Solved in [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)

**Comment by mvinent** [comment]
Solved in [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)
