### ISSUE TITLE
Update SITMUN viewer APP

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-viewer-app#21]
**Describe the bug**
SITMUN viewer APP is using an older version of the API-SITNA modified by IDE Menorca, some functionality is not up-to-date, so, it would be a good idea to update the API-SITNA in the project to match IDE Menorca last developments. Some other issues may be influenced by this change (some even solved).

**Comment by fjlopez** [comment]
Please, complete the description of the task.

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)
