### ISSUE TITLE
Territory list should be in alphabetical order

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-viewer-app#23]
The territory list is not displayed in alphabetical order:

![image](https://github.com/sitmun/sitmun-viewer-app/assets/38311286/6c102aee-3e60-4d77-8573-7cd1625c5de5)

Alphabetical order would be easier for the user.

**Comment by fjlopez** [comment]
@codinachssm @srodriguez7 testing the use of the projects. Update the description/priorities as will.

**Comment by srodriguez7** [comment]
The list of territories is requested from the backend, it should arrive in alphabetical order if we want to display it that way.

**Comment by fjlopez** [comment]
This issue will be addressed in #177 in the backend.
