### ISSUE TITLE
Unable to drag and drop 'geo' files onto the viewer

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-viewer-app#26]
**Describe the bug**
API-SITNA allows you to drop 'geo' (geo, being kml, shp, etc) files onto the viewer. Seems to collide with the Angular environment which contains the viewer.

**To Reproduce**
1. Go to sitmun-viewer
2. Click drag and drop a 'geo' file onto the viewer
4. See error (file opens in a new tab instead being loaded onto the viewer)

**Expected behavior**
Being able to drag and drop files onto the viewer

**Comment by fjlopez** [comment]
@mvinent can you confirm that this bug is a blocker?

**Comment by fjlopez** [comment]
@codinachssm @IDEmenorca do you agree this is not a blocker issue? Which should be the priority of this issue (P0 - blocker, P1 - medium, P2 - low)?

**Comment by codinachssm** [comment]
I think it is a blocking problem as you cannot test the full behavior of this functionality.

**Comment by daniboube** [comment]
Drag and drop control of geographic files within applications has been enabled.

Loading geographic files on the map is possible thanks to an internal control of SITNA, the dataloader. This control can be enabled by submitting the corresponding task from the backend. By doing so, in the right side menu of the applications, the section that allows you to add this type of files will be displayed, loading them through the local file explorer. However, this by default does not enable the 'drag and drop' functionality. To do this, it is necessary that the task arriving from the backend in the response includes a boolean property known as 'enableDragAndDrop'.

With this fix, this condition has been set to true by default in case the 'dataLoader' task is included. However, it would be more advisable for this property to be included in the response that comes from the backend with the map configuration.

I leave the link to the SITNA documentation where this behavior is detailed:
https://sitna.tracasa.es/api/doc/SITNA.control.html#.DataLoaderOptions

To test this, load an application that has this control enabled (for example, the 12/4 application) and drag a valid file onto the map. An icon should appear in the middle of the screen indicating this functionality is active.

**Comment by daniboube** [comment]
Additionally, a serious error that blocked the use of the application in Firefox browsers has been corrected.

When refreshing the page within a map in Firefox, the SITNA HTML elements were duplicated, leaving the application useless and forcing the user to exit and re-enter that map.

This has been fixed in commit 717ca8d66056a52dd3b8741adee5af868f4bc4e7.
