### ISSUE TITLE
Show an error when a tree is incorrect

### ISSUE THREAD

**Issue by srodriguez7** [sitmun/sitmun-viewer-app#28]

**Comment by fjlopez** [comment]
@srodriguez7 
- [ ] Confirm if this issue is related to the behaviour described in https://github.com/sitmun/sitmun-viewer-app/issues/27#issuecomment-2034923378
- [ ] Fill the description of the bug following the template.

**Comment by srodriguez7** [comment]
It's not related to that issue, but to the #14 . 

An incorrect tree should not be able to be selected, that is why the error will be displayed and the tree is not shown in the change tree window

**Comment by fjlopez** [comment]
Is this a new bug different from #14 or the fix to #14?

**Comment by srodriguez7** [comment]
This is a different bug. #14 is fixed as long as the trees in the json are correct

**Comment by fjlopez** [comment]
Could you update the description of the issue with an example that reproduces this bug?

**Comment by daniboube** [comment]
Additionally, a conditional has been added that hides the button to change catalogs when, for an application, there is only one valid catalog or none at all.

**Comment by srodriguez7** [comment]
Responsive
