### ISSUE TITLE
Group layers from diferent services into "Folders" 

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-viewer-app#29]
**Describe the functionality**
We should be able to group different layers (even from different services) into folders which must be clickable, meaning that all layers inside the folder must be added to the map at the same time.

**Comment by fjlopez** [comment]
Explain first the constraint that we have: API SITNA does not support this feature. Also, provide a hint of how do you think which should be the approach for solving this issue and if this would require some support from the backend.

**Comment by mvinent** [comment]
Almost all the logic implemented on [this commit](Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/646a7f039bb9fbbfcb6a3c2762ce7f9bae71dcc7), not market as completed because we'll need to manage the 'carpeta' parameter when it comes through the admin. Right now it's hardcoded (marked with a TODO comment), when the admin returns the parameter we'll have to adapt de code to receive it.

**Comment by fjlopez** [comment]
@mvinent create an issue asking for support in the admin to control the behavior of the folder.

**Comment by fjlopez** [comment]
@codinachssm will test this feature

**Comment by codinachssm** [comment]
I have tested it in the “generic IDE viewer” application.

- I think the behavior of the folders/nodes in the tree is as expected, but there is a layer that contains some error and makes it fail: “RPTI. Sòl rústic. APT Costes”.
- How can I temporarily uncheck (not delete) and with a single click all the loaded layers? Is it possible?
