### ISSUE TITLE
Text "Edición de entidades geográficas" out of its gray box

### ISSUE THREAD

**Issue by rbejar** [sitmun/sitmun-viewer-app#5]
**Describe the bug**
The text "Edición de entidades geográficas" in the left accordion menu is out of its grey box in Chrome-ish browsers, but it fits OK in Firefox.

**To Reproduce**
Load a map viewer (I am using public access/provinces).

**Expected behavior**
The behavior in Firefox seems the right one.

**Screenshots**
Vivaldi:
![image](https://github.com/sitmun/sitmun-viewer-app/assets/1636293/8769fd18-dd96-44f8-b7b1-7c4f32cc0ffe)

Firefox:
![image](https://github.com/sitmun/sitmun-viewer-app/assets/1636293/ac91a30e-0eef-4b17-a1b4-7cd19a11ebf7)

**Desktop (please complete the following information):**
Linux, Vivaldi, Latest, vs Firefox Latest.

**Additional context**
The zoom level in the browser does not seem to be the problem. I can change it but the texts still fit/don't fit in Firefox/Vivaldi.

**Comment by mvinent** [comment]
Control is under development, so right now it's not a real issue.

**Comment by mvinent** [comment]
I think invalid fits better for this issue at this time
