### ISSUE TITLE
Background thumbnail making up

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-viewer-app#53]
**Is your feature request related to a problem? Please describe.**
Every background map should display a different thumbnail in SITMUN viewer acording to what is defined in the SITMUN administrator.

**Describe the solution you'd like**
The thumnail associated to each background map in the viewer should correspond to the image defined in the manager in the respective field (see attached image).

![image](https://github.com/user-attachments/assets/20261be5-8bb2-4935-af8e-a8b7c3727747)

Therefore the sitmun API should attach the corresponding parameter to each background map. 

![image](https://github.com/user-attachments/assets/65340e1d-f130-4e1f-9b80-2262bdb04660)

**Comment by fjlopez** [comment]
@silmeUsil0001 , Is this feasible with the API SITNA? Could you provide a link to the docs?

**Comment by RicardCots** [comment]
I think so, in fact i guess API SITNA is expecting a thumbnail. @mvinent will provide the details.

IDENA example:
![image](https://github.com/user-attachments/assets/1cb1021e-19b7-4008-96a8-50aa3184b4a1)

IDE menorca example:

![image](https://github.com/user-attachments/assets/14af27e1-1863-4647-b59b-7b5edfce3c2e)

**Comment by fjlopez** [comment]
I’ve just pushed changes to `sitmun-backend-core` that address the issue on the server-side. A `thumbnail` property has been added to the background description provided by the API. 

@RicardCots I believe updating the viewer to support this new feature should be straightforward.

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/4b63834ff8534214652e12f0ad89e2d9d5f9f7bb).

**Comment by mvinent** [comment]
Fixed, admin takes the value, API response sends the value and viewer applies it.

Admin:
![image](https://github.com/user-attachments/assets/e05c06a8-2795-4c03-a8c7-0b11c42745c8)

API Response:
![image](https://github.com/user-attachments/assets/6e645be6-df51-47d5-83cf-942674a03fd3)

Viewer:
![image](https://github.com/user-attachments/assets/45f2ed6d-6be7-422a-96e3-7adbafcf5c1c)
