### ISSUE TITLE
Apparently nothing happens when you press the print button... but only apparently.

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-viewer-app#54]
**Describe the bug**
It seems that printing takes longer than usual (compared to other SITNA API viewers) and this causes a user interface problem since the user has no information about what is happening and may think that he has not pressed the button, or that the application has crashed...

Additionally, this behaviour causes errors due to possible user interactions with the application (pressing the print button again, closing the window...).

**To Reproduce**
1. Go to a SITMUN viewer.
2. 2. Click on tools->Print
3. Click on the download button to download the PDF file.
4. Observe how long it takes and how the user has no information about what is happening. Alternatively try interacting with the application (close the print window, press the button again...). 

**Expected behavior**
Printing faster (at least as fast as it is in other SITNA API viewers) and the user is also informed by a progress bar or a process gif.

**Screenshots**
![image](https://github.com/user-attachments/assets/48506ef9-4ab0-4b7a-adde-bce0de645080)

**Comment by silmeUsil0001** [comment]
Solved changing the image to a valid URL
