### ISSUE TITLE
WMS add button seems to do nothing

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-viewer-app#6]
**Describe the bug**
WMS add button seems to do nothing

**To Reproduce**
1. Go to 'Tools'-> 'Añadir mapa'
2. introduce new WMS service in the textbox
3. Click 'Añadir nuevo servicio'
4. Nothing happens
5. See error on debug console

**Expected behavior**
An external WMS layer should be loaded into tree control.

**Screenshots**
![err2](https://github.com/sitmun/sitmun-viewer-app/assets/6534787/fb48bbe6-4a4e-4f49-a0a8-893586c28509)

It seems that the problems might be related to the configuration of the ExternalWMS contrrol in config.json file. Suggestions must be declarated and instanciated to null

**Comment by fjlopez** [comment]
@mvinent @silmeUsil0001 which should be the priority of this bug?

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)
