### ISSUE TITLE
When closing the measuring tool, it does not close the working windows

### ISSUE THREAD

**Issue by ibarzrm** [sitmun/sitmun-viewer-app#63]
**Describe the bug**
When the tool is closed with the red cross, the measurement and profile windows remain open. These must be closed manually, otherwise you can continue measuring.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Draw and measure'
3. Click on type of geometry
4. Open profile
5. Close tool
6. See error: Drawing can be continued

**Expected behavior**
Close all windows.

**Screenshots**
![image](https://github.com/user-attachments/assets/918f63e6-bf1a-4dca-b23f-d9c1a1243d3b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fjlopez** [comment]
The viewer work as expected. The symbology of the close icon should be replaced by an arrow (collapse icon)

**Comment by RicardCots** [comment]
![imagen](https://github.com/user-attachments/assets/3cbf5144-4717-4e74-be91-aefb9d05a112)

**Comment by mvinent** [comment]
Added an image showing the 'collapse' option. Solved on [this commit](4b63834ff8534214652e12f0ad89e2d9d5f9f7bb).

**Comment by mvinent** [comment]
Icon changed for an arrow:
![image](https://github.com/user-attachments/assets/75b6690a-b37d-4c98-b7dd-dd4089edeb2f)
