### ISSUE TITLE
The layer is greyed out in the tree within the loaded layers of the viewer and the cartography is visible on the map

### ISSUE THREAD

**Issue by ibarzrm** [sitmun/sitmun-viewer-app#71]
**Describe the bug**
Even if neither the layer nor the source service has a display limitation at any scale, it appears in grey in the tree of loaded layers in the viewer and the cartography is displayed on the map.

Example service: https://sitmun.diba.cat/wms/INSPIRE/NZ

**Expected behavior**
Only show a layer in grey if it is not possible see the cartography at that scale.

**Screenshots**
![image](https://github.com/user-attachments/assets/2f140d88-5ee3-40c5-95dd-ea76a2671809)

![image](https://github.com/user-attachments/assets/2df42cb3-0ef1-4016-bdfa-b8db5b844f2c)

**Comment by fjlopez** [comment]
@mvinent could you review this issue?

**Comment by mvinent** [comment]
The layer name appearing in gray or in black depends on the capabilities' definition. The <MaxScaleDenominator> tag defines the max scale at which the layer name appears in black, after that, the layer name will appear in gray.
The elements of the layer appearing on the map depend on what the server serving them returns, so to match that with the max scale denominator depends on a correct implementation of the service, the client just shows what it receives from the server.

**Comment by ibarzrm** [comment]
Thank you for the information on how the view application works. I have checked the definition of capabilities and service and it is exactly as @mvinent described.
We will review our service to correct it.

**Comment by ibarzrm** [comment]
We have modified capabilities and now the behaviour is correct. Thank you
