### ISSUE TITLE
Incorrect Tree Nested Levels Rendering in Viewer Module

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-viewer-app#8]
**Describe the bug**
Tree nested levels are not set properly when more than 2 levels are needed. If a tree has more than 2 levels, all of them are rendered in a 2-level structure in the viewer module. The issue has been confirmed to be on the client side and not in the backend. (Issue reference: https://github.com/sitmun/sitmun-backend-core/issues/169)

**To Reproduce**
- Go to the administrator and edit tree number 33. In this tree, there are two different levels from the root. The first level (Capas) contains the "pnoa" layer and two other nodes (grupo1 and grupo2). Each of these nodes contains more layers.

![err11](https://github.com/sitmun/sitmun-backend-core/assets/6534787/e74dffb8-cb5e-4b4c-a857-0b079d164818)

- Open the viewer and observe how the tree is rendered. All nodes are displayed at the same level.

![image](https://github.com/sitmun/sitmun-backend-core/assets/6534787/3b08785d-3049-47a8-95f2-bdfddc6bcd64)

**Expected behavior**
The same tree structure as in the Administrator module should be displayed in the viewer module. All nested levels should be correctly represented, allowing users to navigate the tree hierarchy effectively.

**Comment by silmeUsil0001** [comment]
The bug seems to be created in the SITNA treeLayer Control that Silme has modified. Only two nested levels are allowed right now. Silme will investigate how to increase the limitation.

**Comment by IDEmenorca** [comment]
Only one first level is shown by default

![image](https://github.com/sitmun/sitmun-viewer-app/assets/26217441/f559e650-0b1e-4913-9ca3-727576c42973)
![image](https://github.com/sitmun/sitmun-viewer-app/assets/26217441/ec5c2312-29be-48dc-bba5-1563bb20e004)

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/86f50209cf2b989649d461434f0220813ea22a81)
